// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagnosticDto } from "./DiagnosticDto";
import type { ScenarioDto } from "./ScenarioDto";
import type { SourceDto } from "./SourceDto";

export type OpenedSaveDto = { source: SourceDto, scenario: ScenarioDto, diagnostics: Array<DiagnosticDto>, dirty: boolean, revision: bigint, };
