// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ScenarioMutationDto = { "type": "setName", text: string, } | { "type": "setFileName", text: string, } | { "type": "setDescription", text: string, };
