// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ValidationIssueDto } from "./ValidationIssueDto";

export type ValidationResultDto = { revision: bigint, issues: Array<ValidationIssueDto>, };
