use std::fmt::Display;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ArtifactID {
    Unknown(i32),
    UltimateBook,
    UltimateSword,
    UltimateCloak,
    UltimateWand,
    UltimateShield,
    UltimateStaff,
    UltimateCrown,
    GoldenGoose,
    ArcaneNecklace,
    CasterBracelet,
    MageRing,
    WitchesBroach,
    MedalValor,
    MedalCourage,
    MedalHonor,
    MedalDistinction,
    FizbinMisfortune,
    ThunderMace,
    ArmoredGauntlets,
    DefenderHelm,
    GiantFlail,
    Ballista,
    StealthShield,
    DragonSword,
    PowerAxe,
    DivineBreastplate,
    MinorScroll,
    MajorScroll,
    SuperiorScroll,
    ForemostScroll,
    EndlessSackGold,
    EndlessBagGold,
    EndlessPurseGold,
    NomadBootsMobility,
    TravelerBootsMobility,
    RabbitFoot,
    GoldenHorseshoe,
    GamblerLuckyCoin,
    FourLeafClover,
    TrueCompassMobility,
    SailorsAstrolabeMobility,
    EvilEye,
    EnchantedHourglass,
    GoldWatch,
    Skullcap,
    IceCloak,
    FireCloak,
    LightningHelm,
    EvercoldIcicle,
    EverhotLavaRock,
    LightningRod,
    SnakeRing,
    Ankh,
    BookElements,
    ElementalRing,
    HolyPendant,
    PendantFreeWill,
    PendantLife,
    SerenityPendant,
    SeeingEyePendant,
    KineticPendant,
    PendantDeath,
    WandNegation,
    GoldenBow,
    Telescope,
    StatesmanQuill,
    WizardHat,
    PowerRing,
    AmmoCart,
    TaxLien,
    HideousMask,
    EndlessPouchSulfur,
    EndlessVialMercury,
    EndlessPouchGems,
    EndlessCordWood,
    EndlessCartOre,
    EndlessPouchCrystal,
    SpikedHelm,
    SpikedShield,
    WhitePearl,
    BlackPearl,
    MagicBook,
    EditorAnyUltimateArtifact,
    Unused84,
    Unused85,
    Unused86,
    SpellScroll,
    ArmMartyr,
    BreastplateAnduran,
    BroachShielding,
    BattleGarb,
    CrystalBall,
    HeartFire,
    HeartIce,
    HelmetAnduran,
    HolyHammer,
    LegendaryScepter,
    Masthead,
    SphereNegation,
    StaffWizardry,
    SwordBreaker,
    SwordAnduran,
    SpadeNecromancy,
}

impl ArtifactID {
    pub const fn from_i32(value: i32) -> Self {
        match value {
            1 => ArtifactID::UltimateBook,
            2 => ArtifactID::UltimateSword,
            3 => ArtifactID::UltimateCloak,
            4 => ArtifactID::UltimateWand,
            5 => ArtifactID::UltimateShield,
            6 => ArtifactID::UltimateStaff,
            7 => ArtifactID::UltimateCrown,
            8 => ArtifactID::GoldenGoose,
            9 => ArtifactID::ArcaneNecklace,
            10 => ArtifactID::CasterBracelet,
            11 => ArtifactID::MageRing,
            12 => ArtifactID::WitchesBroach,
            13 => ArtifactID::MedalValor,
            14 => ArtifactID::MedalCourage,
            15 => ArtifactID::MedalHonor,
            16 => ArtifactID::MedalDistinction,
            17 => ArtifactID::FizbinMisfortune,
            18 => ArtifactID::ThunderMace,
            19 => ArtifactID::ArmoredGauntlets,
            20 => ArtifactID::DefenderHelm,
            21 => ArtifactID::GiantFlail,
            22 => ArtifactID::Ballista,
            23 => ArtifactID::StealthShield,
            24 => ArtifactID::DragonSword,
            25 => ArtifactID::PowerAxe,
            26 => ArtifactID::DivineBreastplate,
            27 => ArtifactID::MinorScroll,
            28 => ArtifactID::MajorScroll,
            29 => ArtifactID::SuperiorScroll,
            30 => ArtifactID::ForemostScroll,
            31 => ArtifactID::EndlessSackGold,
            32 => ArtifactID::EndlessBagGold,
            33 => ArtifactID::EndlessPurseGold,
            34 => ArtifactID::NomadBootsMobility,
            35 => ArtifactID::TravelerBootsMobility,
            36 => ArtifactID::RabbitFoot,
            37 => ArtifactID::GoldenHorseshoe,
            38 => ArtifactID::GamblerLuckyCoin,
            39 => ArtifactID::FourLeafClover,
            40 => ArtifactID::TrueCompassMobility,
            41 => ArtifactID::SailorsAstrolabeMobility,
            42 => ArtifactID::EvilEye,
            43 => ArtifactID::EnchantedHourglass,
            44 => ArtifactID::GoldWatch,
            45 => ArtifactID::Skullcap,
            46 => ArtifactID::IceCloak,
            47 => ArtifactID::FireCloak,
            48 => ArtifactID::LightningHelm,
            49 => ArtifactID::EvercoldIcicle,
            50 => ArtifactID::EverhotLavaRock,
            51 => ArtifactID::LightningRod,
            52 => ArtifactID::SnakeRing,
            53 => ArtifactID::Ankh,
            54 => ArtifactID::BookElements,
            55 => ArtifactID::ElementalRing,
            56 => ArtifactID::HolyPendant,
            57 => ArtifactID::PendantFreeWill,
            58 => ArtifactID::PendantLife,
            59 => ArtifactID::SerenityPendant,
            60 => ArtifactID::SeeingEyePendant,
            61 => ArtifactID::KineticPendant,
            62 => ArtifactID::PendantDeath,
            63 => ArtifactID::WandNegation,
            64 => ArtifactID::GoldenBow,
            65 => ArtifactID::Telescope,
            66 => ArtifactID::StatesmanQuill,
            67 => ArtifactID::WizardHat,
            68 => ArtifactID::PowerRing,
            69 => ArtifactID::AmmoCart,
            70 => ArtifactID::TaxLien,
            71 => ArtifactID::HideousMask,
            72 => ArtifactID::EndlessPouchSulfur,
            73 => ArtifactID::EndlessVialMercury,
            74 => ArtifactID::EndlessPouchGems,
            75 => ArtifactID::EndlessCordWood,
            76 => ArtifactID::EndlessCartOre,
            77 => ArtifactID::EndlessPouchCrystal,
            78 => ArtifactID::SpikedHelm,
            79 => ArtifactID::SpikedShield,
            80 => ArtifactID::WhitePearl,
            81 => ArtifactID::BlackPearl,
            82 => ArtifactID::MagicBook,
            83 => ArtifactID::EditorAnyUltimateArtifact,
            84 => ArtifactID::Unused84,
            85 => ArtifactID::Unused85,
            86 => ArtifactID::Unused86,
            87 => ArtifactID::SpellScroll,
            88 => ArtifactID::ArmMartyr,
            89 => ArtifactID::BreastplateAnduran,
            90 => ArtifactID::BroachShielding,
            91 => ArtifactID::BattleGarb,
            92 => ArtifactID::CrystalBall,
            93 => ArtifactID::HeartFire,
            94 => ArtifactID::HeartIce,
            95 => ArtifactID::HelmetAnduran,
            96 => ArtifactID::HolyHammer,
            97 => ArtifactID::LegendaryScepter,
            98 => ArtifactID::Masthead,
            99 => ArtifactID::SphereNegation,
            100 => ArtifactID::StaffWizardry,
            101 => ArtifactID::SwordBreaker,
            102 => ArtifactID::SwordAnduran,
            103 => ArtifactID::SpadeNecromancy,
            other => ArtifactID::Unknown(other),
        }
    }

    pub const fn to_i32(self) -> i32 {
        match self {
            ArtifactID::Unknown(value) => value,
            ArtifactID::UltimateBook => 1,
            ArtifactID::UltimateSword => 2,
            ArtifactID::UltimateCloak => 3,
            ArtifactID::UltimateWand => 4,
            ArtifactID::UltimateShield => 5,
            ArtifactID::UltimateStaff => 6,
            ArtifactID::UltimateCrown => 7,
            ArtifactID::GoldenGoose => 8,
            ArtifactID::ArcaneNecklace => 9,
            ArtifactID::CasterBracelet => 10,
            ArtifactID::MageRing => 11,
            ArtifactID::WitchesBroach => 12,
            ArtifactID::MedalValor => 13,
            ArtifactID::MedalCourage => 14,
            ArtifactID::MedalHonor => 15,
            ArtifactID::MedalDistinction => 16,
            ArtifactID::FizbinMisfortune => 17,
            ArtifactID::ThunderMace => 18,
            ArtifactID::ArmoredGauntlets => 19,
            ArtifactID::DefenderHelm => 20,
            ArtifactID::GiantFlail => 21,
            ArtifactID::Ballista => 22,
            ArtifactID::StealthShield => 23,
            ArtifactID::DragonSword => 24,
            ArtifactID::PowerAxe => 25,
            ArtifactID::DivineBreastplate => 26,
            ArtifactID::MinorScroll => 27,
            ArtifactID::MajorScroll => 28,
            ArtifactID::SuperiorScroll => 29,
            ArtifactID::ForemostScroll => 30,
            ArtifactID::EndlessSackGold => 31,
            ArtifactID::EndlessBagGold => 32,
            ArtifactID::EndlessPurseGold => 33,
            ArtifactID::NomadBootsMobility => 34,
            ArtifactID::TravelerBootsMobility => 35,
            ArtifactID::RabbitFoot => 36,
            ArtifactID::GoldenHorseshoe => 37,
            ArtifactID::GamblerLuckyCoin => 38,
            ArtifactID::FourLeafClover => 39,
            ArtifactID::TrueCompassMobility => 40,
            ArtifactID::SailorsAstrolabeMobility => 41,
            ArtifactID::EvilEye => 42,
            ArtifactID::EnchantedHourglass => 43,
            ArtifactID::GoldWatch => 44,
            ArtifactID::Skullcap => 45,
            ArtifactID::IceCloak => 46,
            ArtifactID::FireCloak => 47,
            ArtifactID::LightningHelm => 48,
            ArtifactID::EvercoldIcicle => 49,
            ArtifactID::EverhotLavaRock => 50,
            ArtifactID::LightningRod => 51,
            ArtifactID::SnakeRing => 52,
            ArtifactID::Ankh => 53,
            ArtifactID::BookElements => 54,
            ArtifactID::ElementalRing => 55,
            ArtifactID::HolyPendant => 56,
            ArtifactID::PendantFreeWill => 57,
            ArtifactID::PendantLife => 58,
            ArtifactID::SerenityPendant => 59,
            ArtifactID::SeeingEyePendant => 60,
            ArtifactID::KineticPendant => 61,
            ArtifactID::PendantDeath => 62,
            ArtifactID::WandNegation => 63,
            ArtifactID::GoldenBow => 64,
            ArtifactID::Telescope => 65,
            ArtifactID::StatesmanQuill => 66,
            ArtifactID::WizardHat => 67,
            ArtifactID::PowerRing => 68,
            ArtifactID::AmmoCart => 69,
            ArtifactID::TaxLien => 70,
            ArtifactID::HideousMask => 71,
            ArtifactID::EndlessPouchSulfur => 72,
            ArtifactID::EndlessVialMercury => 73,
            ArtifactID::EndlessPouchGems => 74,
            ArtifactID::EndlessCordWood => 75,
            ArtifactID::EndlessCartOre => 76,
            ArtifactID::EndlessPouchCrystal => 77,
            ArtifactID::SpikedHelm => 78,
            ArtifactID::SpikedShield => 79,
            ArtifactID::WhitePearl => 80,
            ArtifactID::BlackPearl => 81,
            ArtifactID::MagicBook => 82,
            ArtifactID::EditorAnyUltimateArtifact => 83,
            ArtifactID::Unused84 => 84,
            ArtifactID::Unused85 => 85,
            ArtifactID::Unused86 => 86,
            ArtifactID::SpellScroll => 87,
            ArtifactID::ArmMartyr => 88,
            ArtifactID::BreastplateAnduran => 89,
            ArtifactID::BroachShielding => 90,
            ArtifactID::BattleGarb => 91,
            ArtifactID::CrystalBall => 92,
            ArtifactID::HeartFire => 93,
            ArtifactID::HeartIce => 94,
            ArtifactID::HelmetAnduran => 95,
            ArtifactID::HolyHammer => 96,
            ArtifactID::LegendaryScepter => 97,
            ArtifactID::Masthead => 98,
            ArtifactID::SphereNegation => 99,
            ArtifactID::StaffWizardry => 100,
            ArtifactID::SwordBreaker => 101,
            ArtifactID::SwordAnduran => 102,
            ArtifactID::SpadeNecromancy => 103,
        }
    }
}

impl Default for ArtifactID {
    fn default() -> Self {
        ArtifactID::Unknown(0)
    }
}

impl Display for ArtifactID {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ArtifactID::Unknown(value) => write!(f, "Unknown artifact {value}"),
            known => write!(f, "{known:?} ({})", known.to_i32()),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct Artifact {
    pub id: ArtifactID,
    pub ext: i32,
}
