use std::fmt::Display;

/// fheroes2 hero id.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum HeroID {
    Unknown(i32),

    // Succession Wars - Knights
    LordKilburn,
    SirGallanth,
    Ector,
    Gvenneth,
    Tyro,
    Ambrose,
    Ruby,
    Maximus,
    Dimitry,

    // Succession Wars - Barbarians
    Thundax,
    Fineous,
    Jojosh,
    CragHack,
    Jezebel,
    Jaclyn,
    Ergon,
    Tsabu,
    Atlas,

    // Succession Wars - Sorceresses
    Astra,
    Natasha,
    Troyan,
    Vatawna,
    Rebecca,
    Gem,
    Ariel,
    Carlawn,
    Luna,

    // Succession Wars - Warlocks
    Arie,
    Alamar,
    Vesper,
    Crodo,
    Barok,
    Kastore,
    Agar,
    Falagar,
    Wrathmont,

    // Succession Wars - Wizards
    Myra,
    Flint,
    Dawn,
    Halon,
    Myrini,
    Wilfrey,
    Sarakin,
    Kalindra,
    Mandigal,

    // Succession Wars - Necromancers
    Zom,
    Darlana,
    Zam,
    Ranloo,
    Charity,
    Rialdo,
    Roxana,
    Sandro,
    Celia,

    // Succession Wars - Campaign Heroes
    Roland,
    Corlagon,
    Eliza,
    Archibald,
    Halton,
    Brax,

    // Price of Loyalty
    Solmyr,
    Dainwin,
    Mog,
    UncleIvan,
    Joseph,
    Gallavant,
    Elderian,
    Ceallach,
    Drakonia,
    Martine,
    Jarkonas,

    Debug,
}

impl HeroID {
    /// Build from the raw save value.
    pub const fn from_i32(value: i32) -> Self {
        match value {
            1 => HeroID::LordKilburn,
            2 => HeroID::SirGallanth,
            3 => HeroID::Ector,
            4 => HeroID::Gvenneth,
            5 => HeroID::Tyro,
            6 => HeroID::Ambrose,
            7 => HeroID::Ruby,
            8 => HeroID::Maximus,
            9 => HeroID::Dimitry,
            10 => HeroID::Thundax,
            11 => HeroID::Fineous,
            12 => HeroID::Jojosh,
            13 => HeroID::CragHack,
            14 => HeroID::Jezebel,
            15 => HeroID::Jaclyn,
            16 => HeroID::Ergon,
            17 => HeroID::Tsabu,
            18 => HeroID::Atlas,
            19 => HeroID::Astra,
            20 => HeroID::Natasha,
            21 => HeroID::Troyan,
            22 => HeroID::Vatawna,
            23 => HeroID::Rebecca,
            24 => HeroID::Gem,
            25 => HeroID::Ariel,
            26 => HeroID::Carlawn,
            27 => HeroID::Luna,
            28 => HeroID::Arie,
            29 => HeroID::Alamar,
            30 => HeroID::Vesper,
            31 => HeroID::Crodo,
            32 => HeroID::Barok,
            33 => HeroID::Kastore,
            34 => HeroID::Agar,
            35 => HeroID::Falagar,
            36 => HeroID::Wrathmont,
            37 => HeroID::Myra,
            38 => HeroID::Flint,
            39 => HeroID::Dawn,
            40 => HeroID::Halon,
            41 => HeroID::Myrini,
            42 => HeroID::Wilfrey,
            43 => HeroID::Sarakin,
            44 => HeroID::Kalindra,
            45 => HeroID::Mandigal,
            46 => HeroID::Zom,
            47 => HeroID::Darlana,
            48 => HeroID::Zam,
            49 => HeroID::Ranloo,
            50 => HeroID::Charity,
            51 => HeroID::Rialdo,
            52 => HeroID::Roxana,
            53 => HeroID::Sandro,
            54 => HeroID::Celia,
            55 => HeroID::Roland,
            56 => HeroID::Corlagon,
            57 => HeroID::Eliza,
            58 => HeroID::Archibald,
            59 => HeroID::Halton,
            60 => HeroID::Brax,
            61 => HeroID::Solmyr,
            62 => HeroID::Dainwin,
            63 => HeroID::Mog,
            64 => HeroID::UncleIvan,
            65 => HeroID::Joseph,
            66 => HeroID::Gallavant,
            67 => HeroID::Elderian,
            68 => HeroID::Ceallach,
            69 => HeroID::Drakonia,
            70 => HeroID::Martine,
            71 => HeroID::Jarkonas,
            72 => HeroID::Debug,
            other => HeroID::Unknown(other),
        }
    }

    /// Return the raw save value.
    pub const fn to_i32(self) -> i32 {
        match self {
            HeroID::Unknown(value) => value,
            HeroID::LordKilburn => 1,
            HeroID::SirGallanth => 2,
            HeroID::Ector => 3,
            HeroID::Gvenneth => 4,
            HeroID::Tyro => 5,
            HeroID::Ambrose => 6,
            HeroID::Ruby => 7,
            HeroID::Maximus => 8,
            HeroID::Dimitry => 9,
            HeroID::Thundax => 10,
            HeroID::Fineous => 11,
            HeroID::Jojosh => 12,
            HeroID::CragHack => 13,
            HeroID::Jezebel => 14,
            HeroID::Jaclyn => 15,
            HeroID::Ergon => 16,
            HeroID::Tsabu => 17,
            HeroID::Atlas => 18,
            HeroID::Astra => 19,
            HeroID::Natasha => 20,
            HeroID::Troyan => 21,
            HeroID::Vatawna => 22,
            HeroID::Rebecca => 23,
            HeroID::Gem => 24,
            HeroID::Ariel => 25,
            HeroID::Carlawn => 26,
            HeroID::Luna => 27,
            HeroID::Arie => 28,
            HeroID::Alamar => 29,
            HeroID::Vesper => 30,
            HeroID::Crodo => 31,
            HeroID::Barok => 32,
            HeroID::Kastore => 33,
            HeroID::Agar => 34,
            HeroID::Falagar => 35,
            HeroID::Wrathmont => 36,
            HeroID::Myra => 37,
            HeroID::Flint => 38,
            HeroID::Dawn => 39,
            HeroID::Halon => 40,
            HeroID::Myrini => 41,
            HeroID::Wilfrey => 42,
            HeroID::Sarakin => 43,
            HeroID::Kalindra => 44,
            HeroID::Mandigal => 45,
            HeroID::Zom => 46,
            HeroID::Darlana => 47,
            HeroID::Zam => 48,
            HeroID::Ranloo => 49,
            HeroID::Charity => 50,
            HeroID::Rialdo => 51,
            HeroID::Roxana => 52,
            HeroID::Sandro => 53,
            HeroID::Celia => 54,
            HeroID::Roland => 55,
            HeroID::Corlagon => 56,
            HeroID::Eliza => 57,
            HeroID::Archibald => 58,
            HeroID::Halton => 59,
            HeroID::Brax => 60,
            HeroID::Solmyr => 61,
            HeroID::Dainwin => 62,
            HeroID::Mog => 63,
            HeroID::UncleIvan => 64,
            HeroID::Joseph => 65,
            HeroID::Gallavant => 66,
            HeroID::Elderian => 67,
            HeroID::Ceallach => 68,
            HeroID::Drakonia => 69,
            HeroID::Martine => 70,
            HeroID::Jarkonas => 71,
            HeroID::Debug => 72,
        }
    }
}

impl Default for HeroID {
    fn default() -> Self {
        HeroID::Unknown(0)
    }
}

impl Display for HeroID {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            HeroID::Unknown(value) => write!(f, "Unknown hero {value}"),
            known => write!(f, "{known:?} ({})", known.to_i32()),
        }
    }
}
