#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum Spell {
    #[default]
    None,
    Fireball,
    FireBlast,
    LightningBolt,
    ChainLightning,
    Teleport,
    Cure,
    MassCure,
    Resurrect,
    ResurrectTrue,
    Haste,
    MassHaste,
    Slow,
    MassSlow,
    Blind,
    Bless,
    MassBless,
    Stoneskin,
    Steelskin,
    Curse,
    MassCurse,
    HolyWord,
    HolyShout,
    Antimagic,
    Dispel,
    MassDispel,
    Arrow,
    Berserker,
    Armageddon,
    ElementalStorm,
    MeteorShower,
    Paralyze,
    Hypnotize,
    ColdRay,
    ColdRing,
    DisruptingRay,
    DeathRipple,
    DeathWave,
    Dragonslayer,
    Bloodlust,
    AnimateDead,
    MirrorImage,
    Shield,
    MassShield,
    SummonEarthElement,
    SummonAirElement,
    SummonFireElement,
    SummonWaterElement,
    Earthquake,
    ViewMines,
    ViewResources,
    ViewArtifacts,
    ViewTowns,
    ViewHeroes,
    ViewAll,
    IdentifyHero,
    SummonBoat,
    DimensionDoor,
    TownGate,
    TownPortal,
    Visions,
    Haunt,
    SetEarthGuardian,
    SetAirGuardian,
    SetFireGuardian,
    SetWaterGuardian,
    // Placeholders for a random spell of the corresponding level and should not be added to the spell book.
    Random,
    Random1,
    Random2,
    Random3,
    Random4,
    Random5,
    // This spell is exclusively a built-in monster spell and should not be added to the spell book.
    Petrify,

    Unknown(i32),
}

impl Spell {
    pub const fn from_i32(value: i32) -> Self {
        match value {
            0 => Spell::None,
            1 => Spell::Fireball,
            2 => Spell::FireBlast,
            3 => Spell::LightningBolt,
            4 => Spell::ChainLightning,
            5 => Spell::Teleport,
            6 => Spell::Cure,
            7 => Spell::MassCure,
            8 => Spell::Resurrect,
            9 => Spell::ResurrectTrue,
            10 => Spell::Haste,
            11 => Spell::MassHaste,
            12 => Spell::Slow,
            13 => Spell::MassSlow,
            14 => Spell::Blind,
            15 => Spell::Bless,
            16 => Spell::MassBless,
            17 => Spell::Stoneskin,
            18 => Spell::Steelskin,
            19 => Spell::Curse,
            20 => Spell::MassCurse,
            21 => Spell::HolyWord,
            22 => Spell::HolyShout,
            23 => Spell::Antimagic,
            24 => Spell::Dispel,
            25 => Spell::MassDispel,
            26 => Spell::Arrow,
            27 => Spell::Berserker,
            28 => Spell::Armageddon,
            29 => Spell::ElementalStorm,
            30 => Spell::MeteorShower,
            31 => Spell::Paralyze,
            32 => Spell::Hypnotize,
            33 => Spell::ColdRay,
            34 => Spell::ColdRing,
            35 => Spell::DisruptingRay,
            36 => Spell::DeathRipple,
            37 => Spell::DeathWave,
            38 => Spell::Dragonslayer,
            39 => Spell::Bloodlust,
            40 => Spell::AnimateDead,
            41 => Spell::MirrorImage,
            42 => Spell::Shield,
            43 => Spell::MassShield,
            44 => Spell::SummonEarthElement,
            45 => Spell::SummonAirElement,
            46 => Spell::SummonFireElement,
            47 => Spell::SummonWaterElement,
            48 => Spell::Earthquake,
            49 => Spell::ViewMines,
            50 => Spell::ViewResources,
            51 => Spell::ViewArtifacts,
            52 => Spell::ViewTowns,
            53 => Spell::ViewHeroes,
            54 => Spell::ViewAll,
            55 => Spell::IdentifyHero,
            56 => Spell::SummonBoat,
            57 => Spell::DimensionDoor,
            58 => Spell::TownGate,
            59 => Spell::TownPortal,
            60 => Spell::Visions,
            61 => Spell::Haunt,
            62 => Spell::SetEarthGuardian,
            63 => Spell::SetAirGuardian,
            64 => Spell::SetFireGuardian,
            65 => Spell::SetWaterGuardian,
            66 => Spell::Random,
            67 => Spell::Random1,
            68 => Spell::Random2,
            69 => Spell::Random3,
            70 => Spell::Random4,
            71 => Spell::Random5,
            72 => Spell::Petrify,
            other => Spell::Unknown(other),
        }
    }

    pub const fn to_i32(self) -> i32 {
        match self {
            Spell::None => 0,
            Spell::Fireball => 1,
            Spell::FireBlast => 2,
            Spell::LightningBolt => 3,
            Spell::ChainLightning => 4,
            Spell::Teleport => 5,
            Spell::Cure => 6,
            Spell::MassCure => 7,
            Spell::Resurrect => 8,
            Spell::ResurrectTrue => 9,
            Spell::Haste => 10,
            Spell::MassHaste => 11,
            Spell::Slow => 12,
            Spell::MassSlow => 13,
            Spell::Blind => 14,
            Spell::Bless => 15,
            Spell::MassBless => 16,
            Spell::Stoneskin => 17,
            Spell::Steelskin => 18,
            Spell::Curse => 19,
            Spell::MassCurse => 20,
            Spell::HolyWord => 21,
            Spell::HolyShout => 22,
            Spell::Antimagic => 23,
            Spell::Dispel => 24,
            Spell::MassDispel => 25,
            Spell::Arrow => 26,
            Spell::Berserker => 27,
            Spell::Armageddon => 28,
            Spell::ElementalStorm => 29,
            Spell::MeteorShower => 30,
            Spell::Paralyze => 31,
            Spell::Hypnotize => 32,
            Spell::ColdRay => 33,
            Spell::ColdRing => 34,
            Spell::DisruptingRay => 35,
            Spell::DeathRipple => 36,
            Spell::DeathWave => 37,
            Spell::Dragonslayer => 38,
            Spell::Bloodlust => 39,
            Spell::AnimateDead => 40,
            Spell::MirrorImage => 41,
            Spell::Shield => 42,
            Spell::MassShield => 43,
            Spell::SummonEarthElement => 44,
            Spell::SummonAirElement => 45,
            Spell::SummonFireElement => 46,
            Spell::SummonWaterElement => 47,
            Spell::Earthquake => 48,
            Spell::ViewMines => 49,
            Spell::ViewResources => 50,
            Spell::ViewArtifacts => 51,
            Spell::ViewTowns => 52,
            Spell::ViewHeroes => 53,
            Spell::ViewAll => 54,
            Spell::IdentifyHero => 55,
            Spell::SummonBoat => 56,
            Spell::DimensionDoor => 57,
            Spell::TownGate => 58,
            Spell::TownPortal => 59,
            Spell::Visions => 60,
            Spell::Haunt => 61,
            Spell::SetEarthGuardian => 62,
            Spell::SetAirGuardian => 63,
            Spell::SetFireGuardian => 64,
            Spell::SetWaterGuardian => 65,
            Spell::Random => 66,
            Spell::Random1 => 67,
            Spell::Random2 => 68,
            Spell::Random3 => 69,
            Spell::Random4 => 70,
            Spell::Random5 => 71,
            Spell::Petrify => 72,
            Spell::Unknown(value) => value,
        }
    }
}
